ALTER TABLE movies ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE songs ADD COLUMN IF NOT EXISTS slug VARCHAR(255);

CREATE UNIQUE INDEX IF NOT EXISTS movies_slug_unique ON movies (slug);
CREATE UNIQUE INDEX IF NOT EXISTS songs_slug_unique ON songs (slug);
